/*************************************************************************
 
	Script Name:	LP_BAT_LAB_ORDERS.PRG
	Description:	Batch Print Lab Order Report in OPS scheduler for
			specified locations in specified order.
 
	Date Written:	Februaruy-2-2008
	Written by:	Nestor Llerena
			Lucile Packard Children's
 
 *************************************************************************
			    Special Instructions
 *************************************************************************
 
 *************************************************************************
			    Revision Information
 *************************************************************************
 Rev	Date	 By		Comments
 ------	-------- --------------	------------------------------------------
 001	02/02/08 N. Llerena	Initial Development
 002	03/28/08 M. Avila	Add 1N stop 2N
 003	01/22/09 I. Todd	Split 1N to 1NHEMEONC AND 1NSTEMCELL
 004	04/17/09 M. Avila	Add 2NCVICU
 005	09/29/10 N. Llerena	Add locations PICN1 and PICN2
 *************************************************************************/
 
DROP PROGRAM LP_BAT_LAB_ORDERS:DBA GO
CREATE PROGRAM LP_BAT_LAB_ORDERS:DBA
 
%INCLUDE CUST_WH:LP_SCRIPT_AUDIT.INC
 
; RunStatus structure used to store Job Completion Stats
; ------------------------------------------------------
RECORD RunStatus (
	1 STATUS[*]
		2 PROG		= c30
		2 STATUS	= c45)
 
; Declare som local variables
declare PRINTER_ID 	= c10
declare FROM_DT 	= c11
declare FROM_TM 	= c5
declare THRU_DT 	= c11
declare THRU_TM 	= c5
 
;Set Printer
;set PRINTER_ID = "ITP1509"
;set PRINTER_ID = "LABC1914"
set PRINTER_ID = "LABC1913"
 
; set a 12 hour window (before and after current time for this report to run
SET FROM_DT = FORMAT(CNVTDATETIME(CURDATE,CURTIME3-4320000),"DD-MMM-YYYY;;Q")
SET FROM_TM = FORMAT(CNVTDATETIME(CURDATE,CURTIME3-4320000),"HH:MM;;Q")
SET THRU_DT = FORMAT(CNVTDATETIME(CURDATE,CURTIME3+4320000),"DD-MMM-YYYY;;Q")
SET THRU_TM = FORMAT(CNVTDATETIME(CURDATE,CURTIME3+4320000),"HH:MM;;Q")
 
; Execute report in the location sequence requested
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"WBN",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"F1MATERNITY",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"F2MATERNITY",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"IICN",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"PICN1",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"	; REV 005
CALL PAUSE(1)											; REV 005
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"2W",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
;EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"1N",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
;EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"2N",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO" ; Replace with 1N
;CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"1NHEMEONC",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"  ; Split 1N
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"1NSTEMCELL",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"  ; Split 1N
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"2ECVICU",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"2NCVICU",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"	;004
CALL PAUSE(1)																						;004
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"2EPICU",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"LD",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"LDR",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"OB",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"PSCN",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"PICN2",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"	; REV 005
CALL PAUSE(1)											; REV 005
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"SCN",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"PAC",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"3N",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"3S",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"3E",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
CALL PAUSE(1)
EXECUTE LP_ORD_LAB_ORDERS_REPORT PRINTER_ID,"3W",FROM_DT,FROM_TM,THRU_DT,THRU_TM,"LAB","NO"
 
 
 
SET REPLY->STATUS_DATA.STATUS = "S"
SET REPLY->STATUS_DATA.SUBEVENTSTATUS[1].TARGETOBJECTVALUE =
	 "LP_BAT_LAB_ORDERS"
 
CALL STORE_AUDIT_DETAIL(0)
END GO
