;*** Generated by translate command; please verify contents before re-including in CCL ***
DROP PROGRAM   1_cust_mp_plst_query : DBA  GO
CREATE PROGRAM  1_cust_mp_plst_query : DBA
 
SET  MODIFY  =  PREDECLARE
 
DECLARE  CNT  =  I4  WITH  NOCONSTANT (0 )
 
SELECT  INTO "nl:"
FROM ( DCP_PL_QUERY_LIST  DPQL ),
( DCP_PL_CUSTOM_ENTRY  CE ),
( ENCOUNTER  E ),
( PERSON  P ),
( DCP_PL_PRIORITIZATION  PR )
 PLAN ( DPQL
WHERE (DPQL.PATIENT_LIST_ID= ptlst_request -> PATIENT_LIST_ID ))
 AND ( CE
WHERE (CE.PATIENT_LIST_ID= ptlst_request -> PATIENT_LIST_ID ))
 AND ( P
WHERE (P.PERSON_ID=CE.PERSON_ID) AND (P.ACTIVE_IND=1 ))
 AND ( E
WHERE (E.ENCNTR_ID=CE.ENCNTR_ID) AND  (( (E.ACTIVE_IND=1 ) )  OR  ((E.ENCNTR_ID=0 ) )) )
 AND ( PR
WHERE (PR.PATIENT_LIST_ID= OUTERJOIN ( ptlst_request -> PATIENT_LIST_ID )) AND (PR.PERSON_ID= OUTERJOIN (
P.PERSON_ID)))
 
 
HEAD REPORT
 CNT =0 ,
 ptlstEncntr_reply -> EXECUTION_DT_TM =DPQL.EXECUTION_DT_TM,
 ptlstEncntr_reply -> EXECUTION_STATUS_CD =DPQL.EXECUTION_STATUS_CD
DETAIL
 CNT =( CNT +1 ),
 
IF ( ( MOD ( CNT , 10 )=1 ) )  STAT = ALTERLIST ( ptlstEncntr_reply -> PATIENTS , ( CNT +9 ))
ENDIF
,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> PERSON_ID =CE.PERSON_ID,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> PERSON_NAME =P.NAME_FULL_FORMATTED,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> ENCNTR_ID =CE.ENCNTR_ID,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> PRIORITY =0 ,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> ACTIVE_IND =1 ,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> ORGANIZATION_ID =E.ORGANIZATION_ID,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> CONFID_LEVEL_CD =E.CONFID_LEVEL_CD,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> CONFID_LEVEL = UAR_GET_COLLATION_SEQ (E.CONFID_LEVEL_CD),
 
IF ( ( ptlstEncntr_reply -> PATIENTS [ CNT ]-> CONFID_LEVEL <0 ) )  ptlstEncntr_reply -> PATIENTS [ CNT ]-> CONFID_LEVEL =0
ENDIF
,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> PRIORITY =PR.PRIORITY,
 ptlstEncntr_reply -> PATIENTS [ CNT ]-> FILTER_IND =0
FOOT REPORT
 STAT = ALTERLIST ( ptlstEncntr_reply -> PATIENTS ,  CNT )
 WITH  NOCOUNTER
 
IF ( ( CNT =0 ) )
SET  ptlstEncntr_reply -> STATUS_DATA -> STATUS  = "Z"
ELSE
SET  ptlstEncntr_reply -> STATUS_DATA -> STATUS  = "S"
ENDIF
 
 END GO
